/***********TABLES*************/
----------------------------------------
--  DDL for Table EMPRUNTS
----------------------------------------
PROMPT Création de la table EMPRUNTS
CREATE TABLE bo.emprunts(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ) NOT NULL,
    livres_id   NUMBER NOT NULL,
    membres_id Number NOT NULL,
    date_emprunt DATE NOT NULL,
    date_retour_prevu DATE GENERATED ALWAYS AS (date_emprunt + 21) VIRTUAL,
    date_retour Date
);
COMMENT ON TABLE bo.emprunts IS 'Table qui gère les emprunts de chaque membre.';
COMMENT ON COLUMN bo.emprunts.livres_id IS 'Id qui fait référence à la tables livres.';
COMMENT ON COLUMN bo.emprunts.membres_id IS 'Id qui fait référence à la table membres.';
COMMENT ON COLUMN bo.emprunts.date_emprunt IS 'Date à laquelle le livre a été emprunté.';
COMMENT ON COLUMN bo.emprunts.date_retour_prevu IS 'Date à laquelle le retour est prévu (21 jours après avoir été emprunté). Colonne virtuelle calculée, pour respecter la consigne dans le tp';
COMMENT ON COLUMN bo.emprunts.date_retour IS 'Date à laquelle le livre a été retourné.';
----------------------------------------
--  DDL for Table LIVRES
----------------------------------------
PROMPT Création de la table LIVRES
CREATE TABLE bo.livres(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    sections_id NUMBER(3) NOT NULL,
    auteurs_id NUMBER NOT NULL,
    genres_id NUMBER NOT NULL,
    ISBN VARCHAR2(50) NOT NULL,
    TITRE VARCHAR2(50) NOT NULL,
    MAISON_EDITION VARCHAR2(50),
    ANNEE_PUBLICATION NUMBER(4),
    LANGAGE VARCHAR2(50),
    PRIX NUMBER(5,2)
);
COMMENT ON TABLE bo.livres IS 'Table qui gère les livres et leurs informations.';

----------------------------------------
--  DDL for Table GENRES
----------------------------------------
PROMPT Création de la table GENRES;
CREATE TABLE bo.genres
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ) NOT NULL,
    nom_genre VARCHAR2(50) NOT NULL
);
COMMENT ON TABLE bo.genres IS 'Table qui gère les genres disponibles.';
----------------------------------------
--  DDL for Table MEMBRES
----------------------------------------
PROMPT Création de la table MEMBRES;
CREATE TABLE bo.membres(
    id NUMBER  GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ) NOT NULL,
    code CHAR(12) NOT NULL,
    prenom VARCHAR2(50) NOT NULL,
    nom VARCHAR2(50) NOT NULL,
    genre CHAR(1),
    date_naissance DATE NOT NULL,
    courriel VARCHAR2(50),
    adresse_ligne1 VARCHAR2(50),
    adresse_ligne2 VARCHAR2(50),
    ville VARCHAR2(50) DEFAULT 'Québec',
    province VARCHAR2(50) DEFAULT 'Québec',
    code_postal VARCHAR2(50),
    pays VARCHAR2(50) DEFAULT 'Canada',
    telephone VARCHAR2(50),
    date_debut_membre Date,
    statut_membre VARCHAR2(15),
    theme_prefere VARCHAR2(15)
);
CREATE SEQUENCE bo.code_membre_seq
  INCREMENT BY 5
    START WITH 5
    MAXVALUE 10000
    NOCYCLE;

COMMENT ON TABLE bo.membres IS 'Table qui gère les membres er leur informations personnelles.';
----------------------------------------
--  DDL for Table AUTEURS
----------------------------------------
PROMPT Création de la table AUTEURS;
CREATE TABLE bo.auteurs(
     id NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ) NOT NULL,
    nom_auteur Varchar2(100) NOT NULL
);
COMMENT ON TABLE bo.auteurs IS 'Table qui gère les auteurs disponibles';
----------------------------------------
--  DDL for Table SECTIONS
----------------------------------------
PROMPT Création de la table SECTIONS;
CREATE TABLE bo.sections(
    id Number(3) NOT NULL,
    nom VARCHAR2(100) NOT NULL,
    description VARCHAR2(255)
);
COMMENT ON TABLE bo.sections IS 'Table qui gère les sections de la bibliothèque.';

/***********contraintes*************/

-- clées primaires
PROMPT Ajout des contraintes de clés primaires;

ALTER TABLE bo.emprunts ADD CONSTRAINT EMPRUNTS_PK PRIMARY KEY (id);
ALTER TABLE bo.livres ADD CONSTRAINT LIVRES_PK PRIMARY KEY (id);
ALTER TABLE bo.genres ADD CONSTRAINT GENRES_PK PRIMARY KEY (id);
ALTER TABLE bo.membres ADD CONSTRAINT MEMBRES_PK PRIMARY KEY (id);
ALTER TABLE bo.auteurs ADD CONSTRAINT AUTEURS_PK PRIMARY KEY (id);
ALTER TABLE bo.sections ADD CONSTRAINT SECTIONS_PK PRIMARY KEY (id);


-- clées étrangères
PROMPT Ajout des contraintes de clés étrangères;

ALTER TABLE bo.emprunts ADD CONSTRAINT EMPRUNTS_FK1 FOREIGN KEY (livres_id) REFERENCES bo.livres (id);

ALTER TABLE bo.emprunts ADD CONSTRAINT EMPRUNTS_FK2 FOREIGN KEY (membres_id) REFERENCES bo.membres (id);

ALTER TABLE bo.livres ADD CONSTRAINT LIVRES_FK1 FOREIGN KEY (sections_id) REFERENCES bo.sections (id);

ALTER TABLE bo.livres ADD CONSTRAINT LIVRES_FK2 FOREIGN KEY (auteurs_id) REFERENCES bo.auteurs (id);

ALTER TABLE bo.livres ADD CONSTRAINT LIVRES_FK3 FOREIGN KEY (genres_id) REFERENCES bo.genres (id);


-- clées uniques

PROMPT Ajout des contraintes UNIQUE;

ALTER TABLE bo.membres ADD CONSTRAINT CODE_UK UNIQUE (code);

-- contraintes
PROMPT Ajout des contraintes CHECK;

-- Genre: M, F ou X
ALTER TABLE bo.membres ADD CONSTRAINT MEMBRES_GENRE CHECK (genre IN ('M', 'F', 'X'));

-- Téléphone: format 000-000-0000
ALTER TABLE bo.membres ADD CONSTRAINT MEMBRES_TELEPHONE CHECK (REGEXP_LIKE(telephone, '^[0-9]{3}-[0-9]{3}-[0-9]{4}$'));

-- Code membre: 4 lettres + 8 chiffres
ALTER TABLE bo.membres ADD CONSTRAINT MEMBRES_CODE CHECK (REGEXP_LIKE(code, '^[A-Z]{4}[0-9]{8}$'));

-- Pays: Canada, États-Unis ou Mexique
ALTER TABLE bo.membres ADD CONSTRAINT MEMBRES_PAYS CHECK (pays IN ('Canada', 'États-Unis', 'Mexique'));

-- Numéro de section: entre 0 et 999
ALTER TABLE bo.sections ADD CONSTRAINT SECTIONS_ID CHECK (id BETWEEN 0 AND 999);

PROMPT La création à fonctionnée !

PROMPT Création de la vue dictionnaire_V;

CREATE OR REPLACE VIEW Dictionnaire_V AS
SELECT utcol.table_name,
       utcol.column_id,
       utcol.column_name,
       utcol.data_type,
       utcol.data_length,
       utcol.data_precision,
       utcol.data_scale,
       utcol.nullable,
       utcomm.comments AS commentaire_table,
       uccomm.comments AS commentaire_colonne,
       cons.constraint_name,
       cons.constraint_type
FROM USER_TAB_COLUMNS utcol
         LEFT JOIN USER_TAB_COMMENTS utcomm
                   ON utcol.table_name = utcomm.table_name
         LEFT JOIN USER_COL_COMMENTS uccomm
                   ON utcol.table_name = uccomm.table_name
                       AND utcol.column_name = uccomm.column_name
         LEFT JOIN user_constraints cons ON utcol.table_name = cons.table_name
WHERE cons.constraint_name NOT LIKE 'SYS_%'
ORDER BY utcol.table_name, utcol.column_id;
